import Link from "next/link";
import { redirect } from "next/navigation";

import { AuthShell } from "@/components/auth-shell";
import { ResetPasswordForm } from "@/components/reset-password-form";
import { getSession } from "@/lib/auth/session";

type ResetPasswordPageProps = {
  searchParams: Promise<{
    token?: string;
  }>;
};

export default async function ResetPasswordPage({
  searchParams,
}: ResetPasswordPageProps) {
  const session = await getSession();

  if (session) {
    redirect("/");
  }

  const { token } = await searchParams;

  return (
    <AuthShell
      eyebrow="New password"
      title="Finish resetting your password."
      description="Use the token from the generated reset link to set your new password."
    >
      {token ? (
        <ResetPasswordForm token={token} />
      ) : (
        <div className="flex flex-col gap-4 rounded-xl border bg-background p-6">
          <h1 className="text-xl font-semibold">Reset link missing</h1>
          <p className="text-sm text-muted-foreground">
            Open this page using the reset link generated by the forgot
            password flow.
          </p>
          <Link
            href="/forgot-password"
            className="text-sm underline underline-offset-4"
          >
            Request a new reset link
          </Link>
        </div>
      )}
    </AuthShell>
  );
}
